---
# tasks file for ufw_allow_ports
- name: Allow ports
  with_items: "{{ configs }}"
  community.general.ufw:
    comment: "{{ item.service }}"
    direction: in
    rule: allow
    proto: tcp
    to_port: "{{ item.port }}"