---
  - name: Mount drives
    with_items: "{{ drives }}"
    ansible.posix.mount:
      src: "/dev/{{ item.device }}1"
      path: "{{ mounts_path }}/{{ item.mount_point }}"

  - name: Create credentials file
    with_items: "{{ smb_credentials }}"
    copy:
      dest: "{{ credentials_path }}/.{{ item.username }}.smb"
      content: |
        username={{ item.username }}
        password={{ item.password }}

  - name: Mount the media share
    with_items: "{{ smb_credentials }}"
    ansible.posix.mount:
      src: "{{ cifs_server_address }}/{{ item.sharepath }}"
      path: "{{ mounts_path }}/{{ item.sharepath }}"
      state: mounted
      fs_type: cifs
      opts: "credentials={{ credentials_path }}/.{{ item.username }}.smb,defaults,noperm"

