---
  - name: Mount drives
    become: yes
    with_items: "{{ var.drives }}"
    ansible.posix.mount:
      src: "/dev/{{ item.device }}1"
      path: "/mnt/{{ item.mount_point }}"

  - name: Create credentials file
    become: yes
    with_items: "{{ var.smb_credentials }}"
    copy:
      dest: "/etc/.{{ item.username }}.smb"
      content: |
        username={{ item.username }}
        password={{ item.password }}

  - name: Mount the media share
    become: yes
    with_items: "{{ var.smb_credentials }}"
    ansible.posix.mount:
      src: "{{ var.cifs_server_address }}/{{ item.sharepath }}"
      path: "/mnt/{{ item.sharepath }}"
      state: mounted
      fs_type: cifs
      opts: "credentials=/etc/.{{ item.username }}.smb,defaults,noperm"

