---
  - name: Include OS-specific variables.
    include_vars: "{{ item }}"
    with_first_found:
      - files:
          - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
          - "vars/{{ ansible_os_family }}.yml"
        skip: true
        
  - name: Install packages
    with_items:
      - "{{ packages }}"
    package:
      name: "{{ item }}"
      state: present

  - name: Change shell to fish
    user:
      name: "{{ template_username }}"
      shell: /usr/bin/fish

  - name: Copy fail2ban config
    template:
      src: jail.local.j2 
      dest: "{{ fail2ban_config_file_path }}"
      owner: root
      group: root 
      mode: 0644