---
  - name: Install packages
    become: yes
    with_items:
      - "{{ packages }}"
    package:
      name: "{{ item }}"
      state: present

  - name: Change shell to fish
    become: yes
    user:
      name: "{{ template_username }}"
      shell: /usr/bin/fish

  - name: Copy fail2ban config
    become: yes
    template: 
      src: jail.local.j2 
      dest: "{{ fail2ban_config_file_path }}"
      owner: root
      group: root 
      mode: 0644