---
# tasks file for run_watchtower
- name: Run watchtower with docker-socket-proxy
  community.general.docker_compose:
    environment: "{{ env_vars }}"
    state: present
    definition: |
      version: "3.7"
      networks:
        proxy:
      services:
        ###############################
        #     docker-socket-proxy     #
        ###############################
        dockerproxy:
          image: tecnativa/docker-socket-proxy
          container_name: dockerproxy
          networks:
            - proxy
          restart: unless-stopped
          environment:
            - POST=1
            - BUILD=1
            - CONTAINERS=1
            - EXEC=1
            - IMAGES=1
            - INFO=1
            - NETWORKS=1
            - SESSION=1
            - SWARM=1
            - SYSTEM=1
            - VOLUMES=1
            - TZ
          expose:
            - 2376
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

        ###############################
        #          watchtower         #
        ###############################
        watchtower:
          image: containrrr/watchtower
          container_name: watchtower
          networks:
            - proxy
          command: -H tcp://dockerproxy:2376 --interval 30
          environment:
            - TZ