---
# tasks file for promtail
- name: Copy Promtail binary
  community.general.docker_container:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml