---
- name: Set authorized key for the new user, copying it from the current user
  ansible.posix.authorized_key:
    user: "{{ template_username }}"
    state: present
    key: "{{ lookup('file', public_key_file) }}"