---
# tasks file for create_filesystem
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-items
  - name: Create filesystem
    loop: "{{ var.drives|flatten(levels=1) }}"
    loop_control:
      extended: yes
    community.general.parted:
      device: "/dev/{{ item.device }}"
      number: "{{ ansible_loop.index }}"
      state: mounted
      fs_type: ext4