---
# tasks file for install_hashicorp_repo
# TODO handle other architectures and distributions
- block:
  when: ansible_distribution == "Ubuntu"
  - name: Add official repo key
    become: yes
    apt_key:
      url: "{{ hashicorp_apt_key_url }}"
      state: present
  - name: Set up the stable repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] {{ hashicorp_ppa_url }} {{ ansible_distribution_release }} main"
      state: present
  - name: Update apt packages
    become: yes
    pakcage:
      update_cache: yes
