---
# tasks file for install_rng_tools
- name: Install rng-tools
  ansible.builtin.apt:
    name: rng-tools
    state: present
    update_cache: yes
# https://www.nico-maas.de/?p=1562
- name: Setup hardware rng
  ansible.builtin.lineinfile:
    line: "HRNGDEVICE={{ rng_device_file }}"
    file: "{{ rng_config_file }}"
  notify: restart_rng-tools