---
  - name: Install mosh (MObile SHell)
    become: yes
    package:
      name: mosh
      state: present

  - name: Install fish 
    become: yes
    package:
      name: fish
      state: present

  - name: Install fail2ban package 
    become: yes
    package: 
      name: fail2ban
      state: present

  - name: Change shell to fish
    become: yes
    user:
      name: "{{ template_username }}"
      shell: /usr/bin/fish

  - name: Copy fail2ban config
    become: yes
    copy: 
      src: jail.local 
      dest: /etc/fail2ban/jail.local 
      owner: root
      group: root 
      mode: 0644

  - name: Install cifs-utils
    become: yes
    package:
      name: cifs-utils
      state: present

  - name: Resize logical volume
    become: yes
    community.general.lvg:
      vg: ubuntu-vg
      pvs: /dev/sda3
      pvresize: yes

