---
# tasks file for install_veracrypt
- name: Add unofficial PPA
  ansible.builtin.apt_repository:
    repo: "{{ ppa_url }}"
    state: present

- name: Install the VeraCrypt package
  package:
    name: veracrypt
    state: present