---
  # Ubuntu
  - name: Install mosh (MObile SHell) on Ubuntu
    when: ansible_distribution == "Ubuntu"
    become: yes
    apt:
      name: mosh
      state: present
  - name: Install fish on Ubuntu
    become: yes
    when: ansible_distribution == "Ubuntu"
    apt:
      name: fish
      state: present
      update_cache: yes
  #CentOS
  - name: Install mosh (MObile SHell) on CentOS
    when: ansible_distribution == "CentOS"
    become: yes
    dnf:
      name: mosh
      state: present
  - name: Install fish on CentOS
    when: ansible_distribution == "CentOS"
    become: yes
    dnf:
      name: fish
      state: present
  - name: Install unattended upgrades on CentOS
    when: ansible_distribution == "CentOS"
    become: yes
    dnf:
      name: dnf-automatic
      state: present

  - name: Change shell to fish
    become: yes
    user:
      name: toor
      shell: /usr/bin/fish