---
  - name: Install mosh (MObile SHell)
    become: yes
    package:
      name: mosh
      state: present

  - name: Install fish 
    become: yes
    package:
      name: fish
      state: present

  - name: Install fail2ban package 
    become: yes
    package: 
      name: fail2ban
      state: present

  - name: Change shell to fish
    become: yes
    user:
      name: "{{ template_username }}"
      shell: /usr/bin/fish

  - name: Copy fail2ban config
    become: true
    copy: 
      src: jail.local 
      dest: /etc/fail2ban/jail.local 
      owner: root
      group: root 
      mode: 0644

  - name: Revert network device naming
    become: yes
    notify: update_grub
    lineinfile:
      state: present
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=\"\"'
      line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"