---
  # Ubuntu
  - name: Install mosh (MObile SHell) on Ubuntu
    when: ansible_distribution == 'Ubuntu'
    become: yes
    apt:
      name: mosh
      state: present

  - name: Install fish on Ubuntu
    become: yes
    when: ansible_distribution == 'Ubuntu'
    apt:
      name: fish
      state: present

  - name: Install fail2ban package on Ubuntu
    apt: 
      name: fail2ban
      state: present
    when: ansible_distribution=='Ubuntu'
    become: yes

  #CentOS
  - name: Install mosh (MObile SHell) on CentOS
    when: ansible_distribution == 'CentOS'
    become: yes
    dnf:
      name: mosh
      state: present

  - name: Install fish on CentOS
    when: ansible_distribution == 'CentOS'
    become: yes
    dnf:
      name: fish
      state: present

  - name: Install unattended upgrades on CentOS
    when: ansible_distribution == 'CentOS'
    become: yes
    dnf:
      name: dnf-automatic
      state: present

  - name: Change shell to fish
    become: yes
    user:
      name: "{{ template_username }}"
      shell: /usr/bin/fish

  - name: Install fail2ban package on CentOS
    dnf: 
      name: fail2ban
      state: present
    when: ansible_distribution=='CentOS'
    become: yes

  # Both
  - name: Copy fail2ban config
    copy: 
      src: jail.local 
      dest: /etc/fail2ban/jail.local 
      owner: root
      group: root 
      mode: 0644
    become: yes