---
  # Ubuntu
  - name: Install Netdata dependencies
    become: true
    when: ansible_distribution == "Ubuntu"
    apt:
      name:
        [
          "zlib1g-dev",
          "uuid-dev",
          "libuv1-dev",
          "liblz4-dev",
          "libjudy-dev",
          "libssl-dev",
          "libmnl-dev",
          "gcc",
          "make",
          "git",
          "autoconf",
          "autoconf-archive",
          "autogen",
          "automake",
          "pkg-config",
          "curl",
          "python",
          "cmake",
        ]
      state: present
      update_cache: yes
  - name: Clone Netdata repo
    become: true
    when: ansible_distribution == "Ubuntu"
    git:
      depth: "1"
      dest: /opt/netdata
      repo: https://github.com/netdata/netdata.git
  - name: Get Netdata status
    become: true
    when: ansible_distribution == "Ubuntu"
    stat:
      path: /opt/netdata
    register: netdata_clone
  - name: Install Netdata using the script in the repo
    become: true
    when: ansible_distribution == "Ubuntu" and netdata_clone.stat.isdir | default(False) and netdata_clone.stat.isdir
    shell: bash netdata-installer.sh --dont-wait --libs-are-really-here
    args:
      chdir: /opt/netdata
    notify: start_netdata

  # CentOS
  - name: Download Netdata repo script
    when: ansible_distribution == "CentOS"
    ansible.builtin.get_url:
      url: https://packagecloud.io/install/repositories/netdata/netdata/script.rpm.sh
      dest: /tmp/
      mode: 0755
  - name: Execute Netdata repo script
    become: true
    when: ansible_distribution == "CentOS"
    shell: sh script.rpm.sh
    args:
      chdir: /tmp/
  - name: Install Netdata
    when: ansible_distribution == "CentOS"
    become: true
    ansible.builtin.dnf:
      name: netdata
      state: present