---
- name: Install Cloud-Init
  become: yes
  package:
    name: cloud-init
    state: present

- name: Remove unused Cloud-Init file
  become: yes
  file:
    path: /etc/cloud/cloud.cfg.d/99-installer.cfg
    state: absent

- name: Configure /etc/cloud/cloud.cfg.d/99_pve.cfg
  become: yes
  copy:
    content: |
      datasource_list: [ NoCloud, ConfigDrive ]
    dest: /etc/cloud/cloud.cfg.d/99_pve.cfg
    mode: u=rw,g=rw,o=rw

- name: Clean up Cloud-Init installation
  become: yes
  block:
    - name: Attempting Cloud-Init clean
      command: cloud-init clean -s -l
      become: yes

  rescue:
    - name: Manually clean Cloud-Init files
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/cloud/instances
        - /var/log/cloud-init.log
        - /var/log/cloud-init-output.log

- name: cloud-init | Enabling cloud-init.service
  become: yes
  service:
    name: cloud-init.service
    enabled: yes