---
- name: Install Cloud-Init
  package:
    name: cloud-init
    state: present

- name: Remove unused Cloud-Init file
  file:
    path: "{{ cloud_init_config_path }}/{{ default_cloud_init_file }}"
    state: absent

- name: Configure datasource list
  copy:
    content: |
      datasource_list: [ NoCloud, ConfigDrive ]
    dest: "{{ cloud_init_config_path }}/{{ cloud_init_file }}"
    mode: '0644'

- name: Clean up Cloud-Init installation
  block:
    - name: Attempting Cloud-Init clean
      command: cloud-init clean -s -l
      register: result
  rescue:
    - name: Print error message
      debug:
        msg: |
          Error while calling cloud-init clean. Manually cleaning up installation files.
          
          {{ result }}
    - name: Manually clean Cloud-Init files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ cloud_init_dirs }}"

- name: Enable cloud-init.service
  service:
    name: cloud-init.service
    enabled: yes