---
# tasks file for remove_netplan
- name: Update cache
  apt:
    update_cache: yes

- name: Install ifupdown
  apt:
    name: ifupdown
    state: present

- name: Remove netplan.io
  apt:
    name: netplan.io
    state: absent
    purge: yes

- name: Delete Netplan directory
  file:
    state: absent
    path: /etc/netplan/

- name: Create network interfaces directory
  copy:
    force: yes
    dest: "/etc/network/interfaces"
    content: |
      auto eth0
      iface eth0 inet dhcp

- name: Revert network device naming
  notify: update_grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=\"\"'
    line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
