---
# tasks file for install_golang
- name: Install unofficial golang PPA
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: "{{ golan_ppa }}"
    state: present

- name: Install golang
  package:
    name: golang-go
    state: present