---
# tasks file for setup_raspi_display
  - name: Install dependencies
    with_items:
      - python3
      - python3-pip
    package:
      name: "{{ item }}"
      state: present

  - name: Install pip dependencies
    with_items:
      - ssd1306-infobutton
    pip:
      executable: /usr/lib/python3/dist-packages/pip
      name: "{{ item }}"
      state: present

  - name: Move python script for front panel
    copy:
      src: setup_display.py
      dest: /opt/

  - name: Move the systemd service file into place
    copy:
      src: start_display.service
      dest: /lib/systemd/system/