---
- name: Install EPEL repo
  dnf:
    name: epel-release
    state: present
    update_cache: true
- name: Enable CentOS8 PowerTools repo
  # NB: doesn't run command  `dnf config-manager --set-enabled PowerTools` as can't make that idempotent
  # https://github.com/ansible/ansible/issues/46963#issuecomment-722999113
  lineinfile:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    create: false # so raise error if not already installed
    regexp: enabled=
    line: enabled=1