---
# tasks file for install_step
  - name: Copy Step (x86)
    become: yes
    when: ansible_architecture is "x86_64"
    copy:
      src: step_0.15.13_amd64/bin/step
      dest: /usr/local/bin

  - name: Copy Step (arm86)
    become: yes
    when: ansible_architecture is "arm64"
    copy:
      src: step_0.15.13_amd64/bin/step
      dest: /usr/local/bin

  - name: Bootstrap
    become: yes
    command:
      cmd: "step ca bootstrap --install --ca-url=https://{{ ca_url }} --fingerprint={{ ca_fingerprint }}"
