---
- name: Create Samba credential files
  become: true
  loop: "{{ credentials }}"
  template:
    src: ../files/smb_credentials.jinja2
    dest: "{{ credentials_directory }}/.{{ item.name }}.smb"
    mode: 600
    owner: root
    group: root

- name: Create Samba mount targets
  become: true
  loop: "{{ credentials }}"
  file:
    path: "{{ mounts_directory }}/{{ item.name }}"
    state: directory

- name: Mount the Samba volumes
  become: true
  loop: "{{ credentials }}"
  mount:
    src: "//{{ samba_server_address }}/{{ item.name }}"
    path: "{{ mounts_directory }}/{{ item.name }}"
    opts: "credentials={{ credentials_directory }}/{{ item.name }}.smb,defaults,file_mode=0777,dir_mode=0777,iocharset=utf8,uid=1000,gid=1000 0 0"
    state: mounted
    fstype: cifs